import 'promise-polyfill/src/polyfill';
import 'fetch-polyfill/fetch';
// import './Array.includes';
// import './Array.fill';
// import './Array.find';
// import './Array.forEach';
// import './Array.from';
// import './NodeList.forEach';
// import './Element.closest';
// import './Element.classList';
import 'element-scroll-polyfill';
// import './ChildNode.remove';
// import './Object.assign';
// import './String.endsWith';
// import './String.includes';
// import './String.repeat';
// import './String.startsWith';
// import 'core-js';
import 'es6-shim';
import 'es6-symbol/implement';
